# MST_TenantSettings テーブル詳細定義
table_name: "MST_TenantSettings"
logical_name: "テナント設定"
category: "マスタ系"

# 改版履歴
revision_history:
  - version: "1.0.0"
    date: "2025-06-01"
    author: "開発チーム"
    changes: "初版作成 - テナント設定マスタテーブルの詳細定義"

# テーブル概要・目的
overview: |
  MST_TenantSettings（テナント設定）は、マルチテナントシステムにおける各テナント固有の設定情報を管理するマスタテーブルです。
  
  主な目的：
  - テナント別システム設定の管理
  - 機能有効/無効の制御設定
  - UI・表示設定のカスタマイズ
  - 業務ルール・制限値の設定
  - 外部連携設定の管理
  
  このテーブルは、マルチテナント管理機能において各テナントの個別要件に対応する重要なマスタデータです。

# 業務固有カラム定義
business_columns:
  - name: id
    logical: ID
    type: VARCHAR
    length: 50
    null: false
    unique: true
    encrypted: false
    description: プライマリキー（UUID）
    
  - name: tenant_id
    logical: テナントID
    type: VARCHAR
    length: 50
    null: false
    unique: false
    encrypted: false
    description: 設定対象のテナントID（MST_Tenantへの参照）
    
  - name: setting_category
    logical: 設定カテゴリ
    type: ENUM
    length: null
    null: false
    unique: false
    encrypted: false
    description: 設定の分類（SYSTEM:システム、UI:ユーザーインターフェース、BUSINESS:業務、SECURITY:セキュリティ、INTEGRATION:連携）
    enum_values: ['SYSTEM', 'UI', 'BUSINESS', 'SECURITY', 'INTEGRATION']
    
  - name: setting_key
    logical: 設定キー
    type: VARCHAR
    length: 100
    null: false
    unique: false
    encrypted: false
    description: 設定項目の識別キー（例：max_users、theme_color、skill_approval_required等）
    
  - name: setting_name
    logical: 設定名
    type: VARCHAR
    length: 200
    null: false
    unique: false
    encrypted: false
    description: 設定項目の表示名
    
  - name: setting_description
    logical: 設定説明
    type: TEXT
    length: null
    null: true
    unique: false
    encrypted: false
    description: 設定項目の詳細説明
    
  - name: data_type
    logical: データ型
    type: ENUM
    length: null
    null: false
    unique: false
    encrypted: false
    description: 設定値のデータ型（STRING:文字列、INTEGER:整数、BOOLEAN:真偽値、JSON:JSON、DECIMAL:小数）
    enum_values: ['STRING', 'INTEGER', 'BOOLEAN', 'JSON', 'DECIMAL']
    
  - name: setting_value
    logical: 設定値
    type: TEXT
    length: null
    null: true
    unique: false
    encrypted: false
    description: 実際の設定値（文字列として格納、data_typeに応じて解釈）
    
  - name: default_value
    logical: デフォルト値
    type: TEXT
    length: null
    null: true
    unique: false
    encrypted: false
    description: 設定のデフォルト値
    
  - name: validation_rules
    logical: バリデーションルール
    type: TEXT
    length: null
    null: true
    unique: false
    encrypted: false
    description: 設定値のバリデーションルール（JSON形式）
    
  - name: is_required
    logical: 必須フラグ
    type: BOOLEAN
    length: null
    null: false
    unique: false
    encrypted: false
    description: 設定が必須かどうか
    default: false
    
  - name: is_encrypted
    logical: 暗号化フラグ
    type: BOOLEAN
    length: null
    null: false
    unique: false
    encrypted: false
    description: 設定値を暗号化するかどうか
    default: false
    
  - name: is_system_managed
    logical: システム管理フラグ
    type: BOOLEAN
    length: null
    null: false
    unique: false
    encrypted: false
    description: システムが自動管理する設定かどうか
    default: false
    
  - name: is_user_configurable
    logical: ユーザー設定可能フラグ
    type: BOOLEAN
    length: null
    null: false
    unique: false
    encrypted: false
    description: テナント管理者が変更可能かどうか
    default: true
    
  - name: display_order
    logical: 表示順序
    type: INTEGER
    length: null
    null: false
    unique: false
    encrypted: false
    description: 管理画面での表示順序
    default: 0
    
  - name: effective_from
    logical: 有効開始日時
    type: TIMESTAMP
    length: null
    null: true
    unique: false
    encrypted: false
    description: 設定が有効になる日時
    
  - name: effective_until
    logical: 有効終了日時
    type: TIMESTAMP
    length: null
    null: true
    unique: false
    encrypted: false
    description: 設定が無効になる日時
    
  - name: last_modified_by
    logical: 最終更新者
    type: VARCHAR
    length: 50
    null: true
    unique: false
    encrypted: false
    description: 設定を最後に更新したユーザーID

# 業務固有インデックス
business_indexes:
  - name: idx_tenant_settings_tenant_key
    columns: [tenant_id, setting_key]
    unique: true
    description: テナント別設定キー検索用（一意）
    
  - name: idx_tenant_settings_category
    columns: [setting_category]
    unique: false
    description: 設定カテゴリ別検索用
    
  - name: idx_tenant_settings_configurable
    columns: [is_user_configurable]
    unique: false
    description: ユーザー設定可能フラグ検索用
    
  - name: idx_tenant_settings_system_managed
    columns: [is_system_managed]
    unique: false
    description: システム管理フラグ検索用
    
  - name: idx_tenant_settings_display_order
    columns: [tenant_id, setting_category, display_order]
    unique: false
    description: 表示順序検索用
    
  - name: idx_tenant_settings_effective
    columns: [effective_from, effective_until]
    unique: false
    description: 有効期間検索用

# 業務固有制約
business_constraints:
  - name: uk_tenant_settings_tenant_key
    type: UNIQUE
    columns: [tenant_id, setting_key]
    description: テナント内設定キー一意制約
    
  - name: chk_tenant_settings_category
    type: CHECK
    condition: "setting_category IN ('SYSTEM', 'UI', 'BUSINESS', 'SECURITY', 'INTEGRATION')"
    description: 設定カテゴリ値チェック制約
    
  - name: chk_tenant_settings_data_type
    type: CHECK
    condition: "data_type IN ('STRING', 'INTEGER', 'BOOLEAN', 'JSON', 'DECIMAL')"
    description: データ型値チェック制約
    
  - name: chk_tenant_settings_effective_period
    type: CHECK
    condition: "effective_until IS NULL OR effective_from IS NULL OR effective_until >= effective_from"
    description: 有効期間整合性チェック制約
    
  - name: chk_tenant_settings_display_order_positive
    type: CHECK
    condition: "display_order >= 0"
    description: 表示順序正数チェック制約

# 外部キー関係
foreign_keys:
  - name: fk_tenant_settings_tenant
    column: tenant_id
    reference_table: MST_Tenant
    reference_column: id
    on_update: CASCADE
    on_delete: CASCADE
    description: テナント管理への外部キー

# サンプルデータ
sample_data:
  - id: "TS001"
    tenant_id: "TENANT001"
    setting_category: "SYSTEM"
    setting_key: "max_users"
    setting_name: "最大ユーザー数"
    setting_description: "このテナントで作成可能な最大ユーザー数"
    data_type: "INTEGER"
    setting_value: "100"
    default_value: "50"
    validation_rules: '{"min": 1, "max": 1000}'
    is_required: true
    is_encrypted: false
    is_system_managed: false
    is_user_configurable: false
    display_order: 1
    effective_from: "2025-01-01 00:00:00"
    effective_until: null
    last_modified_by: "SYSTEM"
    
  - id: "TS002"
    tenant_id: "TENANT001"
    setting_category: "UI"
    setting_key: "theme_color"
    setting_name: "テーマカラー"
    setting_description: "システムのメインテーマカラー"
    data_type: "STRING"
    setting_value: "#2563eb"
    default_value: "#3b82f6"
    validation_rules: '{"pattern": "^#[0-9a-fA-F]{6}$"}'
    is_required: false
    is_encrypted: false
    is_system_managed: false
    is_user_configurable: true
    display_order: 1
    effective_from: null
    effective_until: null
    last_modified_by: "USER001"
    
  - id: "TS003"
    tenant_id: "TENANT001"
    setting_category: "BUSINESS"
    setting_key: "skill_approval_required"
    setting_name: "スキル承認必須"
    setting_description: "スキル登録時に承認が必要かどうか"
    data_type: "BOOLEAN"
    setting_value: "true"
    default_value: "false"
    validation_rules: null
    is_required: true
    is_encrypted: false
    is_system_managed: false
    is_user_configurable: true
    display_order: 1
    effective_from: null
    effective_until: null
    last_modified_by: "USER001"
    
  - id: "TS004"
    tenant_id: "TENANT001"
    setting_category: "SECURITY"
    setting_key: "password_policy"
    setting_name: "パスワードポリシー"
    setting_description: "パスワードの複雑性要件"
    data_type: "JSON"
    setting_value: '{"min_length": 8, "require_uppercase": true, "require_lowercase": true, "require_numbers": true, "require_symbols": false}'
    default_value: '{"min_length": 6, "require_uppercase": false, "require_lowercase": false, "require_numbers": false, "require_symbols": false}'
    validation_rules: '{"type": "object", "properties": {"min_length": {"type": "integer", "minimum": 4, "maximum": 128}}}'
    is_required: true
    is_encrypted: false
    is_system_managed: false
    is_user_configurable: true
    display_order: 1
    effective_from: null
    effective_until: null
    last_modified_by: "USER001"

# 特記事項
notes:
  - "設定はテナント・キーの組み合わせで一意"
  - "setting_valueは文字列として格納し、data_typeに応じて解釈"
  - "暗号化フラグがtrueの場合、setting_valueは暗号化して保存"
  - "validation_rulesはJSON Schema形式で設定値の検証ルールを定義"
  - "有効期間により時限的な設定変更に対応"
  - "システム管理フラグによりシステム専用設定を区別"
  - "表示順序により管理画面での設定項目の並び順を制御"

# 業務ルール
business_rules:
  - "同一テナント内で設定キーは重複不可"
  - "必須設定は削除不可"
  - "システム管理設定はユーザーによる変更不可"
  - "暗号化設定の値は復号化して表示"
  - "有効期間外の設定は無効として扱う"
  - "バリデーションルールに違反する設定値は保存不可"
  - "デフォルト値は設定値が未設定の場合に使用"
  - "設定変更時は最終更新者を記録"
