-- ユーザーロール紐付けテーブル作成DDL
CREATE TABLE MST_UserRole (
    id VARCHAR(50) NOT NULL COMMENT 'ID',
    tenant_id VARCHAR(50) NOT NULL COMMENT 'テナントID',
    is_active BOOLEAN NOT NULL DEFAULT TRUE COMMENT '有効フラグ',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    created_by VARCHAR(50) NOT NULL COMMENT '作成者ID',
    updated_by VARCHAR(50) NOT NULL COMMENT '更新者ID',
    user_id VARCHAR(50) COMMENT 'ユーザーID',
    role_id VARCHAR(50) COMMENT 'ロールID',
    assignment_type ENUM DEFAULT DIRECT COMMENT '割り当て種別',
    assigned_by VARCHAR(50) COMMENT '割り当て者ID',
    assignment_reason TEXT COMMENT '割り当て理由',
    effective_from TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '有効開始日時',
    effective_to TIMESTAMP COMMENT '有効終了日時',
    is_primary_role BOOLEAN DEFAULT False COMMENT '主ロールフラグ',
    priority_order INT DEFAULT 999 COMMENT '優先順序',
    conditions JSON COMMENT '適用条件',
    delegation_source_user_id VARCHAR(50) COMMENT '委譲元ユーザーID',
    delegation_expires_at TIMESTAMP COMMENT '委譲期限',
    auto_assigned BOOLEAN DEFAULT False COMMENT '自動割り当てフラグ',
    requires_approval BOOLEAN DEFAULT False COMMENT '承認要求フラグ',
    approval_status ENUM COMMENT '承認状態',
    approved_by VARCHAR(50) COMMENT '承認者ID',
    approved_at TIMESTAMP COMMENT '承認日時',
    assignment_status ENUM DEFAULT ACTIVE COMMENT '割り当て状態',
    last_used_at TIMESTAMP COMMENT '最終使用日時',
    usage_count INT DEFAULT 0 COMMENT '使用回数',
    PRIMARY KEY (id),
    INDEX idx_tenant (tenant_id),
    INDEX idx_active (is_active),
    INDEX idx_created_at (created_at),
    UNIQUE INDEX idx_user_role (user_id, role_id),
    INDEX idx_user_id (user_id),
    INDEX idx_role_id (role_id),
    INDEX idx_assignment_type (assignment_type),
    INDEX idx_assigned_by (assigned_by),
    INDEX idx_effective_period (effective_from, effective_to),
    INDEX idx_primary_role (user_id, is_primary_role),
    INDEX idx_assignment_status (assignment_status),
    INDEX idx_approval_status (approval_status),
    INDEX idx_delegation_source (delegation_source_user_id),
    CONSTRAINT fk_userrole_user FOREIGN KEY (user_id) REFERENCES MST_UserAuth(user_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_userrole_role FOREIGN KEY (role_id) REFERENCES MST_Role(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_userrole_assigned_by FOREIGN KEY (assigned_by) REFERENCES MST_UserAuth(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_userrole_delegation_source FOREIGN KEY (delegation_source_user_id) REFERENCES MST_UserAuth(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_userrole_approved_by FOREIGN KEY (approved_by) REFERENCES MST_UserAuth(user_id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ユーザーロール紐付け';
