-- ユーザー認証情報テーブル作成DDL
CREATE TABLE MST_UserAuth (
    id VARCHAR(50) NOT NULL COMMENT 'ID',
    tenant_id VARCHAR(50) NOT NULL COMMENT 'テナントID',
    is_active BOOLEAN NOT NULL DEFAULT TRUE COMMENT '有効フラグ',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    created_by VARCHAR(50) NOT NULL COMMENT '作成者ID',
    updated_by VARCHAR(50) NOT NULL COMMENT '更新者ID',
    user_id VARCHAR(50) COMMENT 'ユーザーID',
    login_id VARCHAR(100) COMMENT 'ログインID',
    password_hash VARCHAR(255) COMMENT 'パスワードハッシュ',
    password_salt VARCHAR(100) COMMENT 'パスワードソルト',
    employee_id VARCHAR(50) COMMENT '社員ID',
    account_status ENUM DEFAULT ACTIVE COMMENT 'アカウント状態',
    last_login_at TIMESTAMP COMMENT '最終ログイン日時',
    last_login_ip VARCHAR(45) COMMENT '最終ログインIP',
    failed_login_count INT DEFAULT 0 COMMENT 'ログイン失敗回数',
    last_failed_login_at TIMESTAMP COMMENT '最終ログイン失敗日時',
    password_changed_at TIMESTAMP COMMENT 'パスワード変更日時',
    password_expires_at TIMESTAMP COMMENT 'パスワード有効期限',
    mfa_enabled BOOLEAN DEFAULT False COMMENT '多要素認証有効',
    mfa_secret VARCHAR(255) COMMENT '多要素認証シークレット',
    recovery_token VARCHAR(255) COMMENT '復旧トークン',
    recovery_token_expires_at TIMESTAMP COMMENT '復旧トークン有効期限',
    session_timeout INT COMMENT 'セッションタイムアウト',
    external_auth_provider VARCHAR(50) COMMENT '外部認証プロバイダ',
    external_auth_id VARCHAR(255) COMMENT '外部認証ID',
    PRIMARY KEY (id),
    INDEX idx_tenant (tenant_id),
    INDEX idx_active (is_active),
    INDEX idx_created_at (created_at),
    UNIQUE INDEX idx_user_id (user_id),
    UNIQUE INDEX idx_login_id (login_id),
    UNIQUE INDEX idx_employee_id (employee_id),
    INDEX idx_account_status (account_status),
    INDEX idx_last_login (last_login_at),
    INDEX idx_password_expires (password_expires_at),
    INDEX idx_external_auth (external_auth_provider, external_auth_id),
    CONSTRAINT fk_userauth_employee FOREIGN KEY (employee_id) REFERENCES MST_Employee(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ユーザー認証情報';
