-- 部署マスタテーブル作成DDL
CREATE TABLE MST_Department (
    id VARCHAR(50) NOT NULL COMMENT 'ID',
    tenant_id VARCHAR(50) NOT NULL COMMENT 'テナントID',
    is_active BOOLEAN NOT NULL DEFAULT TRUE COMMENT '有効フラグ',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    created_by VARCHAR(50) NOT NULL COMMENT '作成者ID',
    updated_by VARCHAR(50) NOT NULL COMMENT '更新者ID',
    department_code VARCHAR(20) COMMENT '部署コード',
    department_name VARCHAR(100) COMMENT '部署名',
    department_name_short VARCHAR(50) COMMENT '部署名略称',
    parent_department_id VARCHAR(50) COMMENT '親部署ID',
    department_level INT COMMENT '部署レベル',
    department_type ENUM COMMENT '部署種別',
    manager_id VARCHAR(50) COMMENT '部署長ID',
    deputy_manager_id VARCHAR(50) COMMENT '副部署長ID',
    cost_center_code VARCHAR(20) COMMENT 'コストセンターコード',
    budget_amount DECIMAL(15,2) COMMENT '予算額',
    location VARCHAR(200) COMMENT '所在地',
    phone_number VARCHAR(20) COMMENT '代表電話番号',
    email_address VARCHAR(255) COMMENT '代表メールアドレス',
    establishment_date DATE COMMENT '設立日',
    abolition_date DATE COMMENT '廃止日',
    department_status ENUM DEFAULT ACTIVE COMMENT '部署状態',
    sort_order INT COMMENT '表示順序',
    description TEXT COMMENT '部署説明',
    PRIMARY KEY (id),
    INDEX idx_tenant (tenant_id),
    INDEX idx_active (is_active),
    INDEX idx_created_at (created_at),
    UNIQUE INDEX idx_department_code (department_code),
    INDEX idx_parent_department (parent_department_id),
    INDEX idx_department_level (department_level),
    INDEX idx_department_type (department_type),
    INDEX idx_manager (manager_id),
    INDEX idx_status (department_status),
    INDEX idx_cost_center (cost_center_code),
    INDEX idx_sort_order (sort_order),
    CONSTRAINT fk_department_parent FOREIGN KEY (parent_department_id) REFERENCES MST_Department(id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_department_manager FOREIGN KEY (manager_id) REFERENCES MST_Employee(id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_department_deputy FOREIGN KEY (deputy_manager_id) REFERENCES MST_Employee(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='部署マスタ';
