-- ロール情報テーブル作成DDL
CREATE TABLE MST_Role (
    id VARCHAR(50) NOT NULL COMMENT 'ID',
    tenant_id VARCHAR(50) NOT NULL COMMENT 'テナントID',
    is_active BOOLEAN NOT NULL DEFAULT TRUE COMMENT '有効フラグ',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    created_by VARCHAR(50) NOT NULL COMMENT '作成者ID',
    updated_by VARCHAR(50) NOT NULL COMMENT '更新者ID',
    role_code VARCHAR(20) COMMENT 'ロールコード',
    role_name VARCHAR(100) COMMENT 'ロール名',
    role_name_short VARCHAR(50) COMMENT 'ロール名略称',
    role_category ENUM COMMENT 'ロールカテゴリ',
    role_level INT COMMENT 'ロールレベル',
    parent_role_id VARCHAR(50) COMMENT '親ロールID',
    is_system_role BOOLEAN DEFAULT False COMMENT 'システムロールフラグ',
    is_tenant_specific BOOLEAN DEFAULT False COMMENT 'テナント固有フラグ',
    max_users INT COMMENT '最大ユーザー数',
    role_priority INT DEFAULT 999 COMMENT 'ロール優先度',
    auto_assign_conditions JSON COMMENT '自動割り当て条件',
    role_status ENUM DEFAULT ACTIVE COMMENT 'ロール状態',
    effective_from DATE COMMENT '有効開始日',
    effective_to DATE COMMENT '有効終了日',
    sort_order INT COMMENT '表示順序',
    description TEXT COMMENT 'ロール説明',
    PRIMARY KEY (id),
    INDEX idx_tenant (tenant_id),
    INDEX idx_active (is_active),
    INDEX idx_created_at (created_at),
    UNIQUE INDEX idx_role_code (role_code),
    INDEX idx_role_category (role_category),
    INDEX idx_role_level (role_level),
    INDEX idx_parent_role (parent_role_id),
    INDEX idx_system_role (is_system_role),
    INDEX idx_tenant_specific (is_tenant_specific),
    INDEX idx_role_status (role_status),
    INDEX idx_effective_period (effective_from, effective_to),
    INDEX idx_sort_order (sort_order),
    CONSTRAINT fk_role_parent FOREIGN KEY (parent_role_id) REFERENCES MST_Role(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ロール情報';
