-- 社員基本情報テーブル作成DDL
CREATE TABLE MST_Employee (
    id VARCHAR(50) NOT NULL COMMENT 'ID',
    tenant_id VARCHAR(50) NOT NULL COMMENT 'テナントID',
    is_active BOOLEAN NOT NULL DEFAULT TRUE COMMENT '有効フラグ',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    created_by VARCHAR(50) NOT NULL COMMENT '作成者ID',
    updated_by VARCHAR(50) NOT NULL COMMENT '更新者ID',
    employee_code VARCHAR(20) COMMENT '社員番号',
    full_name VARCHAR(100) COMMENT '氏名',
    full_name_kana VARCHAR(100) COMMENT '氏名カナ',
    email VARCHAR(255) COMMENT 'メールアドレス',
    phone VARCHAR(20) COMMENT '電話番号',
    hire_date DATE COMMENT '入社日',
    birth_date DATE COMMENT '生年月日',
    gender ENUM COMMENT '性別',
    department_id VARCHAR(50) COMMENT '部署ID',
    position_id VARCHAR(50) COMMENT '役職ID',
    job_type_id VARCHAR(50) COMMENT '職種ID',
    employment_status ENUM DEFAULT FULL_TIME COMMENT '雇用形態',
    manager_id VARCHAR(50) COMMENT '上司ID',
    employee_status ENUM DEFAULT ACTIVE COMMENT '在籍状況',
    PRIMARY KEY (id),
    INDEX idx_tenant (tenant_id),
    INDEX idx_active (is_active),
    INDEX idx_created_at (created_at),
    UNIQUE INDEX idx_employee_code (employee_code),
    UNIQUE INDEX idx_email (email),
    INDEX idx_department (department_id),
    INDEX idx_manager (manager_id),
    INDEX idx_status (employee_status),
    INDEX idx_hire_date (hire_date),
    CONSTRAINT fk_employee_department FOREIGN KEY (department_id) REFERENCES MST_Department(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_employee_position FOREIGN KEY (position_id) REFERENCES MST_Position(id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_employee_job_type FOREIGN KEY (job_type_id) REFERENCES MST_JobType(id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_employee_manager FOREIGN KEY (manager_id) REFERENCES MST_Employee(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='社員基本情報';
