-- 権限情報テーブル作成DDL
CREATE TABLE MST_Permission (
    id VARCHAR(50) NOT NULL COMMENT 'ID',
    tenant_id VARCHAR(50) NOT NULL COMMENT 'テナントID',
    is_active BOOLEAN NOT NULL DEFAULT TRUE COMMENT '有効フラグ',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    created_by VARCHAR(50) NOT NULL COMMENT '作成者ID',
    updated_by VARCHAR(50) NOT NULL COMMENT '更新者ID',
    permission_code VARCHAR(50) COMMENT '権限コード',
    permission_name VARCHAR(100) COMMENT '権限名',
    permission_name_short VARCHAR(50) COMMENT '権限名略称',
    permission_category ENUM COMMENT '権限カテゴリ',
    resource_type VARCHAR(50) COMMENT 'リソース種別',
    action_type ENUM COMMENT 'アクション種別',
    scope_level ENUM COMMENT 'スコープレベル',
    parent_permission_id VARCHAR(50) COMMENT '親権限ID',
    is_system_permission BOOLEAN DEFAULT False COMMENT 'システム権限フラグ',
    requires_conditions BOOLEAN DEFAULT False COMMENT '条件要求フラグ',
    condition_expression TEXT COMMENT '条件式',
    risk_level INT DEFAULT 1 COMMENT 'リスクレベル',
    requires_approval BOOLEAN DEFAULT False COMMENT '承認要求フラグ',
    audit_required BOOLEAN DEFAULT False COMMENT '監査要求フラグ',
    permission_status ENUM DEFAULT ACTIVE COMMENT '権限状態',
    effective_from DATE COMMENT '有効開始日',
    effective_to DATE COMMENT '有効終了日',
    sort_order INT COMMENT '表示順序',
    description TEXT COMMENT '権限説明',
    PRIMARY KEY (id),
    INDEX idx_tenant (tenant_id),
    INDEX idx_active (is_active),
    INDEX idx_created_at (created_at),
    UNIQUE INDEX idx_permission_code (permission_code),
    INDEX idx_permission_category (permission_category),
    INDEX idx_resource_action (resource_type, action_type),
    INDEX idx_scope_level (scope_level),
    INDEX idx_parent_permission (parent_permission_id),
    INDEX idx_system_permission (is_system_permission),
    INDEX idx_risk_level (risk_level),
    INDEX idx_permission_status (permission_status),
    INDEX idx_effective_period (effective_from, effective_to),
    CONSTRAINT fk_permission_parent FOREIGN KEY (parent_permission_id) REFERENCES MST_Permission(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='権限情報';
