-- システムログテーブル作成DDL
CREATE TABLE SYS_SystemLog (
    id VARCHAR(50) NOT NULL COMMENT 'ID',
    tenant_id VARCHAR(50) NOT NULL COMMENT 'テナントID',
    is_active BOOLEAN NOT NULL DEFAULT TRUE COMMENT '有効フラグ',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    created_by VARCHAR(50) NOT NULL COMMENT '作成者ID',
    updated_by VARCHAR(50) NOT NULL COMMENT '更新者ID',
    log_level ENUM COMMENT 'ログレベル',
    log_category VARCHAR(50) COMMENT 'ログカテゴリ',
    message TEXT COMMENT 'ログメッセージ',
    user_id VARCHAR(50) COMMENT '実行ユーザーID',
    session_id VARCHAR(100) COMMENT 'セッションID',
    ip_address VARCHAR(45) COMMENT 'IPアドレス',
    user_agent TEXT COMMENT 'ユーザーエージェント',
    request_url TEXT COMMENT 'リクエストURL',
    request_method VARCHAR(10) COMMENT 'HTTPメソッド',
    response_status INT COMMENT 'レスポンスステータス',
    response_time INT COMMENT 'レスポンス時間',
    error_code VARCHAR(20) COMMENT 'エラーコード',
    stack_trace TEXT COMMENT 'スタックトレース',
    request_body TEXT COMMENT 'リクエストボディ',
    response_body TEXT COMMENT 'レスポンスボディ',
    correlation_id VARCHAR(100) COMMENT '相関ID',
    component_name VARCHAR(100) COMMENT 'コンポーネント名',
    thread_name VARCHAR(100) COMMENT 'スレッド名',
    server_name VARCHAR(100) COMMENT 'サーバー名',
    PRIMARY KEY (id),
    INDEX idx_tenant (tenant_id),
    INDEX idx_active (is_active),
    INDEX idx_created_at (created_at),
    INDEX idx_log_level (log_level),
    INDEX idx_log_category (log_category),
    INDEX idx_user_id (user_id),
    INDEX idx_session_id (session_id),
    INDEX idx_ip_address (ip_address),
    INDEX idx_error_code (error_code),
    INDEX idx_correlation_id (correlation_id),
    INDEX idx_component (component_name),
    INDEX idx_server (server_name),
    INDEX idx_response_time (response_time),
    INDEX idx_created_at_level (created_at, log_level),
    CONSTRAINT fk_log_user FOREIGN KEY (user_id) REFERENCES MST_UserAuth(user_id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='システムログ';
