-- スキル情報テーブル作成DDL
CREATE TABLE TRN_SkillRecord (
    id VARCHAR(50) NOT NULL COMMENT 'ID',
    tenant_id VARCHAR(50) NOT NULL COMMENT 'テナントID',
    is_active BOOLEAN NOT NULL DEFAULT TRUE COMMENT '有効フラグ',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
    created_by VARCHAR(50) NOT NULL COMMENT '作成者ID',
    updated_by VARCHAR(50) NOT NULL COMMENT '更新者ID',
    employee_id VARCHAR(50) COMMENT '社員ID',
    skill_item_id VARCHAR(50) COMMENT 'スキル項目ID',
    skill_level INT COMMENT 'スキルレベル',
    self_assessment INT COMMENT '自己評価',
    manager_assessment INT COMMENT '上司評価',
    evidence_description TEXT COMMENT '証跡説明',
    acquisition_date DATE COMMENT '習得日',
    last_used_date DATE COMMENT '最終使用日',
    expiry_date DATE COMMENT '有効期限',
    certification_id VARCHAR(50) COMMENT '関連資格ID',
    skill_category_id VARCHAR(50) COMMENT 'スキルカテゴリID',
    assessment_date DATE COMMENT '評価日',
    assessor_id VARCHAR(50) COMMENT '評価者ID',
    skill_status ENUM DEFAULT ACTIVE COMMENT 'スキル状況',
    learning_hours INT COMMENT '学習時間',
    project_experience_count INT COMMENT 'プロジェクト経験回数',
    PRIMARY KEY (id),
    INDEX idx_tenant (tenant_id),
    INDEX idx_active (is_active),
    INDEX idx_created_at (created_at),
    UNIQUE INDEX idx_employee_skill (employee_id, skill_item_id),
    INDEX idx_employee (employee_id),
    INDEX idx_skill_item (skill_item_id),
    INDEX idx_skill_level (skill_level),
    INDEX idx_skill_category (skill_category_id),
    INDEX idx_certification (certification_id),
    INDEX idx_status (skill_status),
    INDEX idx_expiry_date (expiry_date),
    INDEX idx_assessment_date (assessment_date),
    CONSTRAINT fk_skill_employee FOREIGN KEY (employee_id) REFERENCES MST_Employee(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_skill_item FOREIGN KEY (skill_item_id) REFERENCES MST_SkillItem(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_skill_certification FOREIGN KEY (certification_id) REFERENCES MST_Certification(id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_skill_category FOREIGN KEY (skill_category_id) REFERENCES MST_SkillCategory(id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_skill_assessor FOREIGN KEY (assessor_id) REFERENCES MST_Employee(id) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='スキル情報';
