# YAML形式検証設定ファイル v2.0
# yaml_format_check_enhanced_v2.py 用の設定ファイル

# 必須セクション定義
required_sections:
  - key: "table_name"
    desc: "物理テーブル名"
  - key: "logical_name"
    desc: "論理テーブル名"
  - key: "category"
    desc: "テーブル分類"
  - key: "revision_history"
    desc: "改版履歴（🔴絶対省略禁止）"
  - key: "overview"
    desc: "テーブル概要（🔴絶対省略禁止）"
  - key: "columns"
    desc: "カラム定義"
  - key: "indexes"
    desc: "インデックス定義"
  - key: "constraints"
    desc: "制約定義"
  - key: "foreign_keys"
    desc: "外部キー定義"
  - key: "sample_data"
    desc: "サンプルデータ"
  - key: "notes"
    desc: "特記事項（🔴絶対省略禁止）"
  - key: "rules"
    desc: "業務ルール（🔴絶対省略禁止）"

# 空値許可セクション（設定不要時は空配列/空文字列で定義可能）
empty_allowed_sections:
  - "indexes"
  - "constraints"
  - "foreign_keys"
  - "sample_data"

# 内容品質要件
content_required_sections:
  revision_history:
    min_items: 1
    type: "array"
    description: "改版履歴は最低1エントリ必須"
  overview:
    min_length: 50
    type: "string"
    description: "概要は最低50文字必須"
  columns:
    min_items: 1
    type: "array"
    description: "カラム定義は最低1項目必須"
  notes:
    min_items: 3
    type: "array"
    description: "特記事項は最低3項目必須"
  rules:
    min_items: 3
    type: "array"
    description: "業務ルールは最低3項目必須"

# パフォーマンス設定
performance:
  max_workers: 4  # 並列処理の最大ワーカー数
  timeout: 30     # タイムアウト時間（秒）

# 機能設定
features:
  enable_suggestions: true   # 修正提案の生成
  enable_auto_fix: false     # 自動修正（将来実装予定）
  enable_line_numbers: true  # 行番号表示
  enable_context: true       # コンテキスト表示

# レポート設定
reporting:
  default_format: "markdown"  # デフォルトレポート形式
  include_suggestions: true   # 修正提案をレポートに含める
  include_examples: true      # 例をレポートに含める
  max_errors_display: 10     # 表示する最大エラー数
  max_warnings_display: 5    # 表示する最大警告数

# カスタム検証ルール（将来拡張用）
custom_rules:
  table_name_pattern: "^[A-Z]{3}_[A-Za-z0-9_]+$"  # テーブル名パターン
  logical_name_required: true                       # 論理名必須
  category_values:                                  # 許可されるカテゴリ値
    - "マスタ系"
    - "トランザクション系"
    - "履歴系"
    - "システム系"
    - "ワーク系"
